### ISSUE TITLE
Certificate based authentication

### ISSUE THREAD

**Issue by mathstuf** [CleverCloud/amq-protocol#21]
Fedora uses AMQP for its messaging system. It looks like it authenticates via SSL certificates. Does this map to `SASLMechanism::External`?

**Comment by mathstuf** [comment]
Here are the docs which use the Python library Fedora has to communicate over the message bus: https://fedora-messaging.readthedocs.io/en/stable/quick-start.html#fedora-s-public-broker

**Comment by Keruspe** [comment]
This looks like it's External indeed: https://github.com/fedora-infra/fedora-messaging/blob/1c6c22d21b72e2f13fcb8ad7e3193b735ded2978/fedora_messaging/twisted/service.py#L219

https://docs.rs/lapin/0.39.7/lapin/struct.Connection.html#method.connect_with_identity is what you'll be looking for to use the certificate, I think.

**Comment by Keruspe** [comment]
(Note that this is currently not supported with rustls)

**Comment by mathstuf** [comment]
Hmm. I guess the `Identity::der` is just a concatenation of the CA, cert, and key then?

**Comment by mathstuf** [comment]
Ah, I've now read about PKCS #12 :) .

**Comment by Keruspe** [comment]
Btw, the reason for this being implemented with pkcs#12 is just because native-tls implements it this way, but I’m totally fine with providing another alternative format

**Comment by mathstuf** [comment]
I'm fine with pkcs#12; fewer configuration paths to deal with this way anyways :) . Deployments of what I'm working on might like to share cert chains, but I'm not quite there yet.

**Comment by Keruspe** [comment]
I guess we can close this one then, feel free to open a new issue if something is missing for your usecase when you get to this part
