### ISSUE TITLE
codegen should add Copy where plausible

### ISSUE THREAD

**Issue by mathstuf** [CleverCloud/amq-protocol#22]
The codegen for types ends up with Clone types with nothing but `Boolean`s in them. Codegen should keep track if any non-Copy type was used and add it if it can.

**Comment by Keruspe** [comment]
Makes sense, shouldn’t be too hard to add

**Comment by Keruspe** [comment]
Do you have some types in mind?

**Comment by mathstuf** [comment]
The `Options` ones in particular since they're mostly just a set of bools.

**Comment by Keruspe** [comment]
Si this issue should be in lapin I think, unless you can think of any type
provided by amq-protocol

**Comment by Keruspe** [comment]
Unless you can think of structs provided by amq-protocol, this is fixed by https://github.com/sozu-proxy/lapin/commit/c7681962bbf8f519ec59d104a2666964474bd4f8
