### ISSUE TITLE
AMQPType Deserialize impl should be smarter

### ISSUE THREAD

**Issue by mathstuf** [CleverCloud/amq-protocol#23]
Right now, trying to deserialize a JSON document into a `FieldTable` ends up with serde complaining that the `enum AMQPType` needs annotation. This type should probably manually `impl Deserialize` so that it can ask the types and just stuff them into the right container.

**Comment by Keruspe** [comment]
I’m not sure that’s something we want to do. Do you have an example of how it would work?

**Comment by mathstuf** [comment]
Right now, I have to write:

```json
{ "somefield": { "LongString": "foo" } }
```

instead of being allowed to write:

```json
{ "somefield": "foo" }
```

Though a JSON -> FieldTable converter shouldn't be too hard. Maybe I'll just do that.

**Comment by Keruspe** [comment]
Be careful though, ShortString and LongString are not the same, and if
rabbitmq expects one and you give it the other one, you’ll get shady errors
are the serialisation is not the same so the server will just read garbage.

**Comment by mathstuf** [comment]
Hmm. Good point.
