### ISSUE TITLE
WASM Compatibility

### ISSUE THREAD

**Issue by Gsantomaggio** [CleverCloud/amq-protocol#25]
Hi @Keruspe,
Thank you for this library. 

I was wondering if you are interested in making this library WASM compatible. 
At the moment it does not compile for wasm due to the openssl dependency.   

I already did it here: https://github.com/Gsantomaggio/amq-protocol/tree/amq-protocol-wasm

```shell
git clone  https://github.com/Gsantomaggio/amq-protocol/ .
git checkout amq-protocol-wasm
rustup target add wasm32-unknown-unknown
cargo build --target wasm32-unknown-unknown --release
```

So the idea would be to split the repository in two repos:

- Pure AMQP protocol/types/uri
- TCP part ( that I removed [here](https://github.com/Gsantomaggio/amq-protocol/commit/d84b1169c070edead68047424b8310725652408d)  )

**Comment by Keruspe** [comment]
Hi,

I do not understand, it is already split. Also, the TLS part is optional
and master doesn’t use openssl by default anymore

**Comment by Gsantomaggio** [comment]
Ok, this is maybe my lack of RUST knowledge. 

When I include the project:
```
amq-protocol = { git = "https://github.com/CleverCloud/amq-protocol.git" }
```

it builds everything. 

I will look at how to import only the modules I am interested in. 
Thank you

**Comment by Keruspe** [comment]
you can pass default-features=true

**Comment by Keruspe** [comment]
I meant false obviously
