### ISSUE TITLE
Parser fails for LongString values containing invalid UTF-8

### ISSUE THREAD

**Issue by teozkr** [CleverCloud/amq-protocol#28]
This seems to be emitted by RabbitMQ's AMQP 1.0 plugin for one.

The RabbitMQ GUI handles this by showing Base64-encoded encodings instead for these properties.

**Comment by teozkr** [comment]
I suppose the "proper" fix here would be to switch to returning `Vec<u8>` instead, and letting the user decode as needed. For the 6.0.x series, a workaround could be to switch to using lossy UTF-8 decoding instead.

**Comment by Keruspe** [comment]
Hi,

Thanks for the report. Which field contains invalid utf8 in this case?

**Comment by Keruspe** [comment]
```
4.2.5.3 Strings

AMQP strings are variable length and represented by an integer length followed by zero or more octets ofdata.
AMQP defines two native string types:
Short strings, stored as an 8-bit unsigned integer length followed by zero or more octets of data. Shortstrings can carry up to 255 octets of UTF-8 data, but may not contain binary zero octets.
Long strings, stored as a 32-bit unsigned integer length followed by zero or more octets of data. Longstrings can contain any data.
```

We might want to make LongString `Vec<u8>` but non-utf8 ShortString is invalid according to the specifications

**Comment by teozkr** [comment]
> Thanks for the report. Which field contains invalid utf8 in this case?

The `x-amqp-1.0-properties` header created by RabbitMQ's [AMQP 1.0 plugin](https://github.com/rabbitmq/rabbitmq-amqp1.0/blob/f269948d55a770ea0b449c3c0616ad7f794ac5e0/src/rabbit_amqp1_0_message.erl)
